### ISSUE TITLE
stopped working?

### ISSUE THREAD

**Issue by jonas1015119** [dimdenGD/BetterTweetDeck#3] opened 2023-08-23 03:38 UTC
just reinstalled but oldTD and this, removed all the old instances etc, and the betterTD menu just doesnt show up in TweetDeck, extension says its running normally, options work.

**Comment by jonas1015119** [comment] 2023-08-23 03:40
extension gives the following warning:

Error: Could not establish connection. Receiving end does not exist.
window[this.entrypoint] is not a function
Extension context invalidated.

the connection one might be related to the current TD outage for the user column?

**Comment by TheAGames10** [comment] 2023-08-24 01:18
I haven't been able to install Better Tweetdeck for v3 of Old Tweetdeck since this error keeps popping up when trying to install: 

![Capture](https://github.com/dimdenGD/BetterTweetDeck/assets/111199398/00bbfbe3-64cf-4104-8489-ee7d34b6c4d8)

**Comment by BKeyport** [comment] 2023-08-24 05:56
TheAGames10 - re-read the install instructions, I missed a step to get the same error, you might too.

**Comment by TheAGames10** [comment] 2023-08-24 15:36
Nope, I have done all the steps, and even tried it again with those same steps and got the error.

**Comment by AdamMReese** [comment] 2023-08-25 03:17
My brother and I are facing issues with it. We've tried refreshing, clearing the cache, and even closing the browser, but it's inconsistent. And even when it does appear, it's not functioning properly. We were trying to make the scrollbars thin using it, but it's still showing the default ones.

**Comment by italomartinns** [comment] 2023-08-25 22:13
The domain name changing to "https://twitter.com/i/tweetdeck" made the extension stop working completely, as it's not allowed to change the website

**Comment by dimdenGD** [comment] 2023-08-25 22:17
It is allowed to change it and it works fine after few refresh attempts

**Comment by ZTetriminos** [comment] 2023-08-25 23:29
It's damn inconsistent. I'm trying to make both extensions work together and only got them working right _once_, by reloading the page over and over again.

**Comment by GoldenLumia** [comment] 2023-08-27 06:23
The load success rate seems very low for me as well. Maybe 10-15%.

**Comment by macchky** [comment] 2023-08-27 17:46
@dimdenGD can you rebuild the package for release?

**Comment by dimdenGD** [comment] 2023-08-27 17:47
its already on latest, there were no changes to it

**Comment by GoldenLumia** [comment] 2023-08-27 23:41
> The load success rate seems very low for me as well. Maybe 10-15%.

The low load success seems to be another Vivaldi problem oddly enough, for me at least. Loading the extensions with the same version into Firefox results in a much better average success rate of loading BetterTD.

**Comment by Stanzilla** [comment] 2023-08-31 06:10
They updated it to work with v3 of OldTweetDeck but did not push a new release. cc @dimdenGD

**Comment by LeonBlade** [comment] 2023-09-01 02:08
> The domain name changing to "https://twitter.com/i/tweetdeck" made the extension stop working completely, as it's not allowed to change the website

The extension has the new URL in the manifest, it should still be working. I think something else is the issue.

**Comment by Stanzilla** [comment] 2023-09-01 13:59
> its already on latest, there were no changes to it

I just checked the release and you just updated the assets on the old release, I guess that will be confusing to most people.

**Comment by LeonBlade** [comment] 2023-09-01 23:18
I manually built the latest version and didn't see any difference anyway. There is some critical issue with how the extension is working that is causing this problem that needs to be investigated. Unfortunately, I don't have enough experience working with Chrome extensions to debug it at this time. I can look into it if this issue is not resolved soon and try to figure out why it's not working.

**Comment by BKeyport** [comment] 2023-09-01 23:32
I really wish we could get the original author involved, he'd whip it out
no problem.

**Comment by LeonBlade** [comment] 2023-09-03 11:53
After doing a bit of poking around, I've determined the issue is with a library called `moduleRaid` which seemingly is having issues working as intended. I tried upgrading the library itself but didn't really resolve the issue. I'm not a pro at webpack and I've never even heard of this library before until now. The library itself isn't actually that widely used either and solves a very niche problem, so it's a little tricky of a solve. I'll keep you all updated if I resolve the issue.

**Comment by LeonBlade** [comment] 2023-09-04 15:10
A small update. I've been poking at this here and there and have noticed that if `moduleRaid` is delayed before startup it does seem to resolve the issue. This leads me to believe that something isn't fully initialized before `webpackJsonp` is being parsed.

I'll try to see if there's a reliable way to have this load (right now I'm just simulating it with a few second delay).

**Comment by LeonBlade** [comment] 2023-09-05 00:55
Okay, I think I have a solution here. The issue is technically with OldTweetDeck.

In a recent update to the plugin, there was some feature that allows the OldTweetDeck plugin to dynamically load in the various JS files from Github to allow the dev to update it without having to force a plugin update.

By manually disabling this logic in the code, it works fine. So the plugin needs to compensate for this somehow.

**Comment by dimdenGD** [comment] 2023-09-05 11:40
Fixed it, published new version to releases.

**Closed by dimdenGD** 2023-09-05 11:40 UTC
Labels: bug

**Comment by LeonBlade** [comment] 2023-09-05 23:21
Thank you!

**Comment by GoldenLumia** [comment] 2023-09-06 05:13
Thanks, all fixed on Vivaldi, and Firefox was hardly having problems before, and now it's perfect. Good to see you again @LeonBlade
